/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\3d modals\plane.glb -o .\components\3dHelpers\Plane.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props: any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3d modals/plane.glb') as any
  const { actions } = useAnimations(animations, group) as any
  useEffect(()=>{
    actions.Sketchfab_SceneAction.play()
    
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_Scene" position={[-0.407, -0.138, -0.678]} rotation={[0, -0.242, 0]} scale={0.251}>
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group name="Car_Rig_24">
                  <group name="tire_lndg_rear_l_in001_1" position={[0.01, 0.636, -0.438]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.tire} />
                  </group>
                  <group name="tire_lndg_rear_l_in002_2" position={[0.011, 0.399, -0.07]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.body_texture} />
                  </group>
                  <group name="tire_lndg_rear_l_in003_3" position={[0.027, 0.32, 1.103]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Wwhitepaint} />
                    <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Wwhitepaint} />
                  </group>
                  <group name="tire_lndg_rear_l_in004_4" position={[0.01, 0.314, -0.315]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.plastic_rough_grey_plus} />
                  </group>
                  <group name="tire_lndg_rear_l_in005_5" position={[-0.024, 0.377, 1.456]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.chrome} />
                  </group>
                  <group name="tire_lndg_rear_l_in006_6" position={[0.01, 0.194, 0.753]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.tire} />
                  </group>
                  <group name="tire_lndg_rear_l_in007_7" position={[0.01, 0.409, -0.05]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.chrome} />
                  </group>
                  <group name="tire_lndg_rear_l_in008_8" position={[0.024, 0.176, 3.404]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.metal_yellow} />
                  </group>
                  <group name="tire_lndg_rear_l_in009_9" position={[0.01, 0.622, -0.109]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.body_texture} />
                  </group>
                  <group name="tire_lndg_rear_l_in010_10" position={[0.01, 1.2, -0.839]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.body_texture} />
                    <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.body_texture} />
                    <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.body_texture} />
                  </group>
                  <group name="tire_lndg_rear_l_in012_11" position={[0.007, 1.184, 0.003]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.glass_clear} />
                  </group>
                  <group name="tire_lndg_rear_l_in013_12" position={[0.014, 1.464, -3.464]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.chrome} position={[0.001, 0, 0]} />
                  </group>
                  <group name="tire_lndg_rear_l_in014_13" position={[0.046, 1.328, -1.552]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.light_white} />
                  </group>
                  <group name="tire_lndg_rear_l_in015_14" position={[-0.087, 1, -0.21]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.metal_rough_plus} />
                  </group>
                  <group name="tire_lndg_rear_l_in016_15" position={[0.011, 1.557, 1.382]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.glass_clear} />
                  </group>
                  <group name="tire_lndg_rear_l_in017_16" position={[0.059, 1.321, -0.799]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.chrome} />
                  </group>
                  <group name="tire_lndg_rear_l_in018_17" position={[0.021, 1.79, -1.504]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.plastic_rough_black} />
                  </group>
                  <group name="tire_lndg_rear_l_in019_18" position={[-0.026, 1.157, 1.076]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.plastic_rough_black_plus} />
                  </group>
                  <group name="tire_lndg_rear_l_in020_19" position={[0.011, 1.344, 2.6]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.board} />
                  </group>
                  <group name="tire_lndg_rear_l_in021_20" position={[0.011, 0.825, 0.687]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.metal_rough} />
                  </group>
                  <group name="tire_lndg_rear_l_in022_21" position={[0, 1.373, -1.684]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.chrome} />
                  </group>
                  <group name="tire_lndg_rear_l_in023_22" position={[0.01, 1.2, -0.839]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.carpaint} />
                    <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.carpaint} />
                    <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.carpaint} />
                  </group>
                  <group name="tire_lndg_rear_l_in024_23" position={[0.011, 1.556, 1.382]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.plastic_rough_black} />
                  </group>
                  <group name="tire_lndg_rear_l_in_0" position={[0.01, 1.327, -2.909]} rotation={[0, 1.571, 0]} scale={0.001}>
                    <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.chrome} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d modals/plane.glb')
